# Generated by Django 5.1.6 on 2025-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlenotes', '0002_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news', models.CharField(max_length=500)),
                ('snippet', models.CharField(max_length=500)),
                ('newsurl', models.URLField(max_length=300)),
                ('thumbnail', models.URLField(max_length=300)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
