# Generated by Django 5.1.6 on 2025-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlenotes', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
