# Generated by Django 5.1.6 on 2025-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlenotes', '0005_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
