# Generated by Django 5.1.6 on 2025-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlenotes', '0006_ticker_active_alter_ticker_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
